SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
USE livedb;
GO
DECLARE @_START DATE; SET @_START = GETDATE()-14;
DECLARE @_END DATE; SET @_END= GETDATE();
DECLARE @_REGION VARCHAR(3); SET @_REGION='ASL';

SELECT
	 
	 /* CONVERT datetime to UNIX_TIMESTAMP*/
	 DATEDIFF(SECOND, {d '1970-01-01'}, VisitDateTime) AS [datetime]
	  
	 ,COUNT(EncSeqID) AS value
	From AprEnc
	WHERE VisitDateTime BETWEEN @_START AND @_END
	AND SourceID = @_REGION
GROUP BY DATEPART(hour, VisitDateTime), VisitDateTime
ORDER BY VisitDateTime DESC